// DO NOT CHANGE VARIABLE NAMES
const variables = {
  abdulkabir: "", // verb: unusual or unexpected action "sneeze"
  abraham: "", // noun: unusual clothing accessory "monocle"
  alicia: "centaur", // noun: mythical creature "dragon"
  annie: "", // proper noun: popular fictional location "Wakanda"
  brianna: "mandible", // noun: unusual body part "earlobe"
  chelsea: "", // noun phrase: accident "bicycle crash"
  emma: "sleep", 
  hana: "", // noun: a quirky or unusual item "banjo"
  heela: "", // adjective: quality or characteristic "peculiar"
  huiyi: "", // noun: word that ends in -ship "mentorship"
  jelena: "", // noun: word that rhymes with "phone"
  jenani: "", // noun: a mundane object "toothbrush"
  jessica: "", // adjective: personality trait "optimistic"
  justin: "", // noun: everyday item "spatula"
  katarina: "", // noun: mode of transportation "hoverboard"
  kate: "", // verb: past tense action "walked"
  kristina: "", // adjective: personal characteristic "naive"
  lily: "Pegasus", // noun: mythical figure "Dracula"
  mashal: "", // noun: animal "fish"
  michelle: "", // noun: random emotion "joy"
  mingxia: "cheerful", // adjective: personality descriptor "cheerful"
  saba: "", // noun: a peculiar animal "platypus"
  scarlett: "", // noun: unique trait or characteristic "selfishness"
  shipa: "", // noun: body part "arm"
  stephen: "", // adjective: describing attitude/behavior "overzealous"
  tami: "", // noun: board game "checkers"
  wendy: "", // verb: unexpected or funny activity "juggle pineapples"
  yang: "", // unusual job title "beekeeper"
  yogina: "Software Developer", // noun: profession, occupation, or role "plumber"
  yuanshu: "restless", // adjective: quirky or distinctive trait "fidgety"
};

export default variables;
